server:
  port: 8081
spring:
  datasource:
    username: zty
    password: 123456
    url: jdbc:mysql://62.234.111.74:3306/cute?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.swpu.uchain.exam.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
